program autocheck

  implicit none

  real :: x, y1, y2
  real, parameter :: delx = 1e-6
  real, parameter :: dely = 1e-5

  x = -7.3
  do while ( x < 3.6 )
    call subfec(x, y1)
    call subfec_org(x, y2)
    if ( abs((y2-y1)/y1) > dely ) then
      print *, x, y1, y2, abs((y2-y1)/y1)
      stop "Test of autogenerated subfec failed!"
    endif
    x = x + delx
  enddo

  print *, "Test of autogenerated subfec passed!"

  x = -30.
  do while ( x < 1.7 )
    call subfec2(x, y1)
    call subfec2_org(x, y2)
    if ( abs((y2-y1)/y1) > dely ) then
      print *, x, y1, y2, abs((y2-y1)/y1)
      stop "Test of autogenerated subfec2 failed!"
    endif
    x = x + delx
  enddo

  print *, "Test of autogenerated subfec2 passed!"

end program autocheck
